import { motion } from 'framer-motion';

const ResumeSuggestionList = ({ suggestions = [] }) => {
  return (
    <div className="space-y-6">
      <h3 className="text-lg font-semibold text-gray-900">AI Feedback Suggestions</h3>
      
      <div className="space-y-4">
        {suggestions.map((suggestion, index) => (
          <motion.div
            key={index}
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: index * 0.1 }}
            className="bg-[#fffefb] p-4 rounded-lg shadow-sm border border-gray-100"
          >
            <div className="flex items-start space-x-3">
              <div className="flex-shrink-0">
                <span className="inline-block p-2 bg-[#ffeb85]/20 rounded-full">
                  {suggestion.type === 'improvement' ? '💡' : '✨'}
                </span>
              </div>
              <div>
                <h4 className="text-sm font-medium text-gray-900 mb-1">
                  {suggestion.title}
                </h4>
                <p className="text-sm text-gray-600">
                  {suggestion.description}
                </p>
                {suggestion.example && (
                  <div className="mt-2 p-2 bg-gray-50 rounded text-sm text-gray-600">
                    Example: {suggestion.example}
                  </div>
                )}
              </div>
            </div>
          </motion.div>
        ))}
      </div>

      <div className="mt-4 text-sm text-gray-500">
        <p>These suggestions are generated by AI to help improve your resume's impact.</p>
      </div>
    </div>
  );
};

export default ResumeSuggestionList;